src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/run/toughtype/ToughType.scala

We were leaking untyped trees out of the macro, which crashed
in refchecks.
This commit proactively typechecks the tree returned by `mkZero`.

Fix compiler crash with value class in result position

---

src/main/scala/scala/async/internal/LiveVariables.scala
src/test/scala/scala/async/run/live/LiveVariablesSpec.scala

This commit disabled live variable analysis for intermediate values of type Nothing.
Fixes #104

Avoid masking real errors with NotImplemented awaiting Future[Nothing]

---

src/main/scala/scala/async/internal/LiveVariables.scala
src/test/scala/scala/async/run/live/LiveVariablesSpec.scala

This commit disabled live variable analysis for intermediate values of type Nothing.
Fixes #104
(cherry picked from commit 6353443a0adec384172c38efac3bc96b9d2cbad2)

[backport] Avoid masking real errors with NotImplemented awaiting Future[Nothing]

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/test/scala/scala/async/run/WarningsSpec.scala

During the ANF transform, we were generating a tree of the shape:
{
val temp: Unit = await(futureOfUnit)
temp
()
}
I tried to simplifiy this to avoid creating the temporary value,
but this proved difficult as it would have required changes to
the subsequent state machine transformation.
Even replacing `temp` with `()` made the state machine transform
harder.
So for now, I've just inserted `temp.asInstanceOf[Unit]` to hide
from the compiler warning.
Fixes #74

Avoid compiler warning when awaiting Future[Unit]

---

project/build.properties
src/main/scala/scala/async/internal/AnfTransform.scala

The stack trace and bisection in #119 made me notice that we
are failing to typecheck the cast we generated in the fix for #74.
The ticket doesn't have a reproduction, so I'm submitting this
without a test case.

Avoid leaking untyped trees out of macro

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/run/anf/AnfTransformSpec.scala

Code like:
val x = if (cond) throw new A else throw new B
Was being transformed to:
val ifRes = ???
if (cond) ifRes = throw new A else ifRes = throw new B
val x = ifRes
by way of the use of `gen.mkZero` which throws `???` if the requested type is `Nothing`
This commit special cases `Nothing` typed expressions in a similar manner to `Unit` type expressions.
The example above is now translated to:
if (cond) throw new A else throw new B
val x = throw new IllegalStateException()
Fixed #120

Avoid masking user exception with ??? for Nothing typed expressions

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/AsyncBase.scala
src/main/scala/scala/async/internal/AsyncId.scala
src/main/scala/scala/async/internal/AsyncMacro.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/Lifter.scala
src/main/scala/scala/async/internal/StateAssigner.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/TreeInterrogation.scala
src/test/scala/scala/async/run/late/LateExpansion.scala

Currently, the async transformation is performed during the typer
phase, like all other macros.
We have to levy a few artificial restrictions on whern an async
boundary may be: for instance we don't support await within a
pattern guard. A more natural home for the transform would be
after patterns have been translated.
The test case in this commit shows how to use the async transform
from a custom compiler phase after patmat.
The remainder of the commit updates the implementation to handle
the new tree shapes.
For states that correspond to a label definition, we use `-symbol.id`
as the state ID. This made it easier to emit the forward jumps to when
processing the label application before we had seen the label
definition.
I've also made the transformation more efficient in the way it …

Enable a compiler plugin to use the async transform after patmat

---

src/main/scala/scala/async/internal/AsyncAnalysis.scala
src/main/scala/scala/async/internal/AsyncBase.scala
src/main/scala/scala/async/internal/AsyncMacro.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/run/WarningsSpec.scala

The presentation compiler runs with `-Ymacro-expand:discard`, which
retains the macro expandee in the typechecked trees, rather than
substituting in the expansion. This mode was motivated as a means
to keep IDE functionality working (e.g. completion, navigation,
refactoring) inside macro applications.
However, if one has nested async macro applications, as reported in
the IDE ticket:
https://www.assembla.com/spaces/scala-ide/tickets/1002561
... the expansion of the outer async application was reporting
await calls enclosed by the inner async application.
This change tweaks the traversers used for this analysis to
stop whenever it sees an async.

Avoid spurious "illegal await" error in IDE with nesting

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/AsyncBase.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/FutureSystem.scala
src/main/scala/scala/async/internal/Lifter.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/TreeInterrogation.scala
src/test/scala/scala/async/run/late/LateExpansion.scala

Fixes for the async transform when invoked after pattern's have been translated.
Followup to #141

Late expansion fixes

---

README.md

And mention it's been removed in favour of this library.

Fix dead link to Akka's Dataflow Concurrency

---

src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/FutureSystem.scala
src/main/scala/scala/async/internal/TransformUtils.scala

The current extension point assumes that if a future is in the
completed state, a subsequent call to get the already completed
value will succeed. While this assumption holds for
scala.concurrent.Future, it might not hold for a future system
that has semantics like a weak reference.
This commit uses a single call `getCompleted` to query the state
and get the already completed value. This returns null if the
value is not available.

Rework extension point for checking for already-completed futures

---

.travis.yml
build.sbt
src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/AsyncAnalysis.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/Lifter.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/run/live/LiveVariablesSpec.scala

- method local lazy vals are now encoded as a single ValDef
rather than a ValDef + DefDef pair. We need to treat ValDef-s
with the LAZY flag in the same way as we used to treat the
DefDef.
- Rename one of the symbols `ANF,anf` in the same scope to avoid
generating anonymous class names that differ only in case. The
compiler warned about this one.
- When patching the LabelDefs to have a `Unit` result type, propagate
this other LabelDefs conclude with a jump to that label. Not sure
why, but without this we now hit an error in the backend about the
nonsensical attempt to emit a coercion from void to int.
- Use crossScalaVersions in the build and update the Scala versions
tested in CI.

Compatibility with Scala 2.12.0-RC1

---

README.md

Added dependency information for Maven and SBT so that it is easier for the developers who are new to the library.

 Add dependency information for including in project.

---

src/test/scala/scala/async/run/late/LateExpansion.scala

After this change tests pass also on Windows.
It turns out in the past there was used `sys.props("java.io.tmpdir")` but it was changed during https://github.com/mpociecha/async/commit/549a656fa22af5f7f0c5e89dd6e0a19ed4b604f5. I'm not sure what was the reason.

In tests use tmp dir working on all operating systems

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/AsyncAnalysis.scala
src/main/scala/scala/async/internal/AsyncBase.scala
src/main/scala/scala/async/internal/AsyncId.scala
src/main/scala/scala/async/internal/AsyncMacro.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/AsyncUtils.scala
src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/LiveVariables.scala
src/test/scala/scala/async/TreeInterrogation.scala
src/test/scala/scala/async/run/SyncOptimizationSpec.scala
src/test/scala/scala/async/run/anf/AnfTransformSpec.scala
src/test/scala/scala/async/run/ifelse4/IfElse4.scala
src/test/scala/scala/async/run/match0/Match0.scala

The logging even when disabled was doing (the default case) was doing a significant amount of work (esp the ```logDiagnostics``` parametersl).
Also ```AsyncUtils.verbose``` and ```AsyncUtils.debug``` were computed on every call.
The result of the changes are minor cleanups seen along the way.

Reduce logging overhead and minor cleanups

---

src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/FutureSystem.scala
src/main/scala/scala/async/internal/TransformUtils.scala

- allow custom macros based on async to control error handling, name freshening
- eliminate dead states and compact state id to emit a minimal tableswitch

Improve generated code and flexibility

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/run/WarningsSpec.scala

Unfortunately I wasn't able to extract a test case, but the patch
has been tested to fix a problem on a real world code base.

Fix ANF transform for corner case in late transforms

---

src/test/scala/scala/async/package.scala

we need to handle a Scala version like `2.13.0-pre-5e84129`,
as we see in nightly builds before bincompat is locked down

fix Scala version number handling for 2.13 community build

---

src/test/scala/scala/async/run/anf/AnfTransformSpec.scala
src/test/scala/scala/async/run/await0/Await0Spec.scala
src/test/scala/scala/async/run/block0/AsyncSpec.scala
src/test/scala/scala/async/run/block1/block1.scala
src/test/scala/scala/async/run/exceptions/ExceptionsSpec.scala
src/test/scala/scala/async/run/futures/FutureSpec.scala
src/test/scala/scala/async/run/ifelse0/IfElse0.scala
src/test/scala/scala/async/run/ifelse1/IfElse1.scala
src/test/scala/scala/async/run/ifelse2/ifelse2.scala
src/test/scala/scala/async/run/ifelse3/IfElse3.scala
src/test/scala/scala/async/run/ifelse4/IfElse4.scala
src/test/scala/scala/async/run/match0/Match0.scala
src/test/scala/scala/async/run/toughtype/ToughType.scala

Remove uses of deprecated Future APIs

---

.travis.yml
build.sbt
src/test/scala/scala/async/run/futures/FutureSpec.scala

Remove use of scala.concurrent.forkjoin

---

src/test/scala/scala/async/run/futures/FutureSpec.scala

as discovered by the Scala 2.13 community build
sequel to #188

fixes for 2.13 compatibility

---

.travis.yml
README.md
admin/README.md
build.sbt
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/run/uncheckedBounds/UncheckedBoundsSpec.scala

also upgrade Scala 2.12.4 -> 2.12.6

drop support for Scala 2.11 as of 0.10.0

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/AsyncMacro.scala
src/main/scala/scala/async/internal/AsyncNames.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/FutureSystem.scala
src/main/scala/scala/async/internal/Lifter.scala
src/main/scala/scala/async/internal/LiveVariables.scala
src/main/scala/scala/async/internal/StateSet.scala
src/main/scala/scala/async/internal/TransformUtils.scala
src/test/scala/scala/async/TreeInterrogation.scala
src/test/scala/scala/async/run/anf/AnfTransformSpec.scala

Don't box state IDs in collections.
- Introduce a per-Global store of names
- Avoid double freshening names
- Use $async$ in all names to avoid clashes with, e.g. lambda lifted methods.
If we're in the expr position of a block, the nested state
generation can reuse the successor state.
Also, output .dot graph of state machine in verbose mode.
Sample: https://gist.github.com/88225478b11c118609b9348d61e13630
View with a local Graphviz install or http://graphviz.it/#/gallery/unix.gv
Sample generated from late expansion of:
val result = run(
"""
import scala.async.run.late.{autoawait,lateasync}
case class FixedFoo(foo: Int)
class Foobar(val foo: Int, val bar: Double) {
def guard: Boolean = true
@autoawait @lateasync def getValue = 4.2
@autoawait @lateasync def func(f: Any) = {
("": Any) match …

Performance improvements to the macro

---

build.sbt
src/main/scala/scala/async/internal/Lifter.scala
src/main/scala/scala/async/internal/LiveVariables.scala
src/main/scala/scala/async/internal/TransformUtils.scala

Eliminates the failures reported by the new `testDeterminism` task:
Before:
```
% sbt testDeterminism
[error] java.lang.AssertionError: /Users/jz/code/scala-async/target/scala-2.12/test-classes-baseline/scala/async/neg/LocalClasses0Spec$stateMachine$async$2.class is not equal to /Users/jz/code/scala-async/target/scala-2.12/test-classes/scala/async/neg/LocalClasses0Spec$stateMachine$async$2.class
[error] Use 'last' for the full log.
$ jardiff /Users/jz/code/scala-async/target/scala-2.12/test-classes-baseline /Users/jz/code/scala-async/target/scala-2.12/test-classes
diff --git a/scala/async/run/ifelse4/TestIfElse4Class$stateMachine$async$1.class.asm b/scala/async/run/ifelse4/TestIfElse4Class$stateMachine$async$1.class.asm
index f6f7d26..585e1b5 100644
--- …
```

Determistic output from the async macro

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/test/scala/scala/async/run/late/LateExpansion.scala

Previously, `whyDoYouHateMe` was incorrectly owned by `jerk`,
rather than `pointlessSymbolOwner` after the ANF transform,
which in turn led to:
```
java.util.NoSuchElementException: value whyDoHateMe
at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:425)
at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:424)
at scala.collection.mutable.AnyRefMap.apply(AnyRefMap.scala:180)
at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:390)
at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:354)
```

Fix ownership corruption problem in the awaited expression

---

src/main/scala/scala/async/internal/AnfTransform.scala
src/main/scala/scala/async/internal/AsyncBase.scala
src/main/scala/scala/async/internal/AsyncId.scala
src/main/scala/scala/async/internal/AsyncMacro.scala
src/main/scala/scala/async/internal/AsyncNames.scala
src/main/scala/scala/async/internal/AsyncTransform.scala
src/main/scala/scala/async/internal/ExprBuilder.scala
src/main/scala/scala/async/internal/FutureSystem.scala
src/main/scala/scala/async/internal/Lifter.scala
src/main/scala/scala/async/internal/LiveVariables.scala
src/main/scala/scala/async/internal/ScalaConcurrentAsync.scala
src/main/scala/scala/async/internal/StateSet.scala
src/main/scala/scala/async/internal/TransformUtils.scala

Applying this PR will reduce the compile warnings from 82 to 15, see #197

Fix deprecation warnings

---

NOTICE

The header comments added to the class files in https://github.com/scala/scala-async/pull/212/ refer to a NOTICE file that isn't there. This PR adds that file.

Add missing NOTICE file

---

project/build.properties
project/plugins.sbt

(the accompanying sbt-scala-module upgrade is required, or MiMa breaks)

bump sbt version to 1.3.7 (was 1.3.0)

---

README.md

https://github.com/scala/scala-async/issues/220

Document provided scope dependency on scala-reflect

---

src/main/scala/scala/async/internal/AsyncTransform.scala

Override Function0.apply() with matching parens

---

build.sbt
project/plugins.sbt

PR for #248 
The project cross compiles without any changes, it was only necessary to create a cross project in SBT.
In current configuration project `projJS` can be used to compile / publish Scala.js artifacts, e.g. `projJS/publishLocal`. I have verified against my own project the artifacts obtained this way work with both compile and fastOptJS.
I have no idea what other steps needs to be taken to get this final and published.
If any more changes are necessary from me, feel free to write.

Cross compile for Scala.js
